### PR TITLE
Allow users to synchronize without branch

### PR DESCRIPTION
**Pull request by pierallard**
Simply use [~] in the branch list, and this will create PR from "master" of Github, to the root of Crowdin without branch management.

### CODE REVIEW

**Comment by nidup** [comment]
Imho this default value should be fulfiled by https://github.com/akeneo/nelson/blob/master/src/Akeneo/DependencyInjection/Extension/GithubExtension.php using a symfony configuration class like this http://symfony.com/doc/current/cookbook/bundles/configuration.html 

The branch argument should be mandatory everywhere and you should not have to add the default master branch everywhere

The default value is the responsibility of the extension, it will make all the other classes and methods more understandable and solid ;)

**Comment by pierallard** [comment]
This is already the case, but with ['master'] as default value : https://github.com/akeneo/nelson/blob/master/src/Akeneo/DependencyInjection/Configuration/GithubConfiguration.php#L42

**Comment by nidup** [comment]
Ok, read too quickly, so i don't get why we have to do if baseBranch then master in several methods :)

**Comment by pierallard** [comment]
That's only here for git methods to ensure that the downloaded repository is on "master", before update or before pull request creation.

**Comment by nidup** [comment]
Ok, got it :)

**Pull request merged**
